create table if not exists public.gps_locations (
  id bigint generated by default as identity primary key,
  device_id text not null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  speed double precision,
  heading double precision,
  battery double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists gps_locations_device_time_idx
on public.gps_locations (device_id, recorded_at desc);

alter table public.gps_locations enable row level security;

-- The backend uses the Supabase service-role key, so no public INSERT policy is required.
-- Never put the service-role key inside the Android APK or website.
